name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      clickhouse:
        image: clickhouse/clickhouse-server:23.8.2.7-alpine
        ports:
          - 8123:8123
        options: >-
          --health-cmd="curl --silent --fail http://localhost:8123/ping || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Docker
      run: |
        docker compose -f docker-compose.yml up -d

    - name: Run database migrations
      run: |
        python manage.py migrate

    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings -q

    - name: Stop Docker Compose services
      run: |
        docker compose down
